use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var_os("OUT_DIR").map(std::path::PathBuf::from).expect("OUT_DIR");
    let payloads = Path::new("payloads");
    println!("cargo:rerun-if-changed=payloads");

    let mut dll_names = Vec::new();
    if payloads.is_dir() {
        if let Ok(entries) = fs::read_dir(payloads) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("dll") {
                    dll_names.push(
                        path.file_name()
                            .expect("dll path has file name")
                            .to_string_lossy()
                            .into_owned(),
                    );
                }
            }
        }
    }
    dll_names.sort();

    let mut code = String::from(
        "// @generated by build.rs — do not edit\n\n\
         pub struct EmbeddedDll {\n\
             pub name: &'static str,\n\
             pub bytes: &'static [u8],\n\
         }\n\n\
         pub static EMBEDDED_DLLS: &[EmbeddedDll] = &[\n",
    );
    for name in &dll_names {
        code.push_str(&format!(
            "    EmbeddedDll {{ name: {name:?}, bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/payloads/\", {name:?})) }},\n",
        ));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("embedded_dlls.rs"), code).expect("write embedded_dlls.rs");
}
